"""Add user relationship to Donation

Revision ID: af4952f28985
Revises: eabf9a1cf7a5
Create Date: 2026-09-16 12:20:42.957937

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'af4952f28985'
down_revision = 'eabf9a1cf7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_donation_user_id_user', 'user',
                                    ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_user_id_user',
                                 type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
